# Generated by Django 5.1.6 on 2025-04-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_category_remove_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='article',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='perex',
        ),
        migrations.AddField(
            model_name='article',
            name='health',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.dimension'),
        ),
        migrations.AddField(
            model_name='article',
            name='nature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.nature'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
