# Generated by Django 5.1.6 on 2025-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_dimension_nature_remove_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
