# Generated by Django 5.1.6 on 2025-04-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_article_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.dimension'),
        ),
        migrations.AlterField(
            model_name='article',
            name='nature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.nature'),
        ),
    ]
